{
    'name': 'Tus Pos Scan',
    'version': '16.0.0.1',
    'summary': '',
    'description': '',
    'category': '',
    'author': '',
    'website': '',
    'license': '',
    'depends': ['pos_discount', 'base'],
    'data': [
        'security/ir.model.access.csv',
        'views/boarding_pass.xml',
        'views/pos_order.xml',
        'views/partner.xml',
    ],
    'assets': {
        'point_of_sale.assets': [
            'tus_pos_scan/static/src/xml/SetSaleOrderButton.xml',
            'tus_pos_scan/static/src/xml/iataboardinglist.xml',
            'tus_pos_scan/static/src/xml/iataboardingform.xml',
            'tus_pos_scan/static/src/xml/iataboardingformcreate.xml',
            'tus_pos_scan/static/src/xml/iataboarding.xml',
            'tus_pos_scan/static/src/js/SetSaleOrderButton.js',
            'tus_pos_scan/static/src/js/iataboardinglist.js',
            'tus_pos_scan/static/src/js/iataboardingform.js',
            'tus_pos_scan/static/src/js/iataboardingformcreate.js',
            'tus_pos_scan/static/src/js/iataboarding.js',
            # 'tus_pos_scan/static/src/js/RefundButton.js',
            # 'tus_pos_scan/static/src/js/ProductScreen.js',
            # 'tus_pos_scan/static/src/js/OrderlineCustomerNoteButton.js',
            # 'tus_pos_scan/static/src/js/DiscountButton.js',
            # 'tus_pos_scan/static/src/js/RewardButton.js',
            'tus_pos_scan/static/src/js/models.js',
        ],
    },
    'installable': True,
    'auto_install': False,
}
